### LLaMA inference using RAG

This document will explain the inference using LLaMA by using GPT-4o answers as the RAG.

For RAG, we will use Chroma database. We will use Chunking of 50 words with overlap of 5 words. But complete sentences will be preserved. For the knowledgebase, the answers from both the training and test data of Gpt-4o-mini will be used.

For testing, we will only perform the evaluation using the test data

In [1]:
import os

In [2]:
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

In [3]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from datasets import load_dataset
from tqdm import tqdm
import pandas as pd
import numpy as np
import pickle
import evaluate
import json
import chromadb
from chromadb.config import Settings
from langchain_text_splitters import RecursiveCharacterTextSplitter

/data/mn27889/miniconda3/envs/mental-health-agents/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Enabling progress_apply for pandas

In [4]:
tqdm.pandas()

### Reading the responses of GPT-4o-mini from test and train data

Train Data

In [5]:
ques_list = []
ans_list = []
llama_resp_list = []
gpt_resp_list = []

with open('phase2_data_kabatubare/train_kabatubare.jsonl', 'rb') as file:
    for line in file:
        json_object = json.loads(line)
        ques_list.append(json_object['question'])
        ans_list.append(json_object['answer'])
        llama_resp_list.append(json_object['llama_response_base'])
        gpt_resp_list.append(json_object['gpt_response_base'])
        
train_dataset = pd.DataFrame({'question': ques_list,
                          'answer': ans_list,
                          'llama_response_base': llama_resp_list,
                          'gpt_response_base': gpt_resp_list})
train_dataset

,question,answer,llama_response_base,gpt_response_base
0,i have a small dull ache in my left testicle a...,just give it a rest my friend. it is not likel...,"I'm here to provide you with information, but ...",It's not uncommon for individuals to experienc...
1,i've heard conflicting opinions. 7 weeks of pr...,hi the best thing is to live your life as norm...,Congratulations on the new addition to your fa...,"During pregnancy, there are several dietary re..."
2,my friend slept over that had fever blisters. ...,hi found you this little piece of info. oral h...,I can sense your concern and worry about the s...,I understand that you're feeling very anxious ...
3,what are some common food triggers for migraines?,you can use information from your diary and tr...,"As a medical knowledge assistant, I can provid...",Migraines can be triggered by a variety of fac...
4,why does grey hair itch so much? . why does my...,hair doesn't itch. scalps will itch. there are...,The itchy sensation associated with grey hair ...,Itching in gray hair can be attributed to seve...
...,...,...,...,...
18744,how to make money online? . a brand new approa...,please do not post advertising on webmd answer...,There are many legitimate ways to make money o...,I'm here to assist with health-related inquiri...
18745,what can i eat with the stomach flu? . i can't...,the best foods to eat while feeling nausea are...,"I'm not a doctor, but I can provide some gener...",When you're dealing with stomach flu (viral ga...
18746,what exams and tests help doctors to evaluate ...,doctors can often easily recognize ringworm wh...,"Ringworm of the scalp, also known as tinea cap...",To evaluate or test individuals for ringworm o...
18747,could i be pregnant?,the only way to know for sure you're pregnant ...,"I'm not a medical professional, but I can prov...",Whether you could be pregnant depends on sever...
18748,if i have an anal fissure should i see a gastr...,that is really up to you. most anal fissures h...,While it's ultimately up to you to decide who ...,"If you have an anal fissure, it's usually appr..."

Test Data

In [6]:
ques_list = []
ans_list = []
llama_resp_list = []
gpt_resp_list = []

with open('phase2_data_kabatubare/test_kabatubare.jsonl', 'rb') as file:
    for line in file:
        json_object = json.loads(line)
        ques_list.append(json_object['question'])
        ans_list.append(json_object['answer'])
        llama_resp_list.append(json_object['llama_response_base'])
        gpt_resp_list.append(json_object['gpt_response_base'])
        
test_dataset = pd.DataFrame({'question': ques_list,
                          'answer': ans_list,
                          'llama_response_base': llama_resp_list,
                          'gpt_response_base': gpt_resp_list})
test_dataset

,question,answer,llama_response_base,gpt_response_base
0,i don't have periods due to taking nuvaring. h...,you really shouldn't worry about getting pregn...,I'm happy to help you with your concern. Since...,If you're using NuvaRing and have missed it by...
1,when you can't digest food. my daughter is 38 ...,i'm sorry your daughter is having a hard time....,I'm so sorry to hear that your daughter is exp...,I'm sorry to hear about your daughter's strugg...
2,8 wks post-hemorrhoidectomy. knife-like pain o...,i'm sorry you're going through this. hemorrhoi...,"I'm not a doctor, but I can try to provide som...",I'm sorry to hear that you're experiencing the...
3,i sometimes feel a mild discomfort under my le...,after reading your full statement i would also...,"I'm not a medical professional, but I can try ...","I'm not a doctor, but I can offer some general..."
4,i had sex about 12 hours ago and i'm noticing ...,hi ok if your shaved and this is on your pubic...,"I'm not a medical professional, but I can prov...",It's good that you're paying attention to chan...
...,...,...,...,...
4683,bright blood in stool for a while now burning ...,hi but as your not really well now i still thi...,"I'm not a doctor, but I can provide some gener...","I'm not a doctor, but the symptoms you're desc..."
4684,i feel fine i'm in a great mood but food taste...,well i'm happy you're in a good mood anyway! i...,"I'm glad you're feeling fine overall, but the ...",It's good to hear that you're feeling fine and...
4685,i have recently had unprotected sex and both m...,"you had unprotected sex? it is your ""other"" he...",I'm here to provide you with information and g...,Experiencing irritation on the head of the pen...
4686,is there a coated naproxen medication to preve...,all over-the-counter and prescription-strength...,"Yes, there are coated naproxen medications ava...","Yes, there are formulations of naproxen that a..."
4687,what are some nonimpact activities for people ...,non-impact exercise program for people with os...,There are several non-impact activities that c...,"For people with osteoporosis, engaging in non-..."

Combining both the test and train data into a single dataframe

In [7]:
comp_dataset = pd.concat([train_dataset, test_dataset], axis=0).reset_index(drop=True)
comp_dataset

,question,answer,llama_response_base,gpt_response_base
0,i have a small dull ache in my left testicle a...,just give it a rest my friend. it is not likel...,"I'm here to provide you with information, but ...",It's not uncommon for individuals to experienc...
1,i've heard conflicting opinions. 7 weeks of pr...,hi the best thing is to live your life as norm...,Congratulations on the new addition to your fa...,"During pregnancy, there are several dietary re..."
2,my friend slept over that had fever blisters. ...,hi found you this little piece of info. oral h...,I can sense your concern and worry about the s...,I understand that you're feeling very anxious ...
3,what are some common food triggers for migraines?,you can use information from your diary and tr...,"As a medical knowledge assistant, I can provid...",Migraines can be triggered by a variety of fac...
4,why does grey hair itch so much? . why does my...,hair doesn't itch. scalps will itch. there are...,The itchy sensation associated with grey hair ...,Itching in gray hair can be attributed to seve...
...,...,...,...,...
23432,bright blood in stool for a while now burning ...,hi but as your not really well now i still thi...,"I'm not a doctor, but I can provide some gener...","I'm not a doctor, but the symptoms you're desc..."
23433,i feel fine i'm in a great mood but food taste...,well i'm happy you're in a good mood anyway! i...,"I'm glad you're feeling fine overall, but the ...",It's good to hear that you're feeling fine and...
23434,i have recently had unprotected sex and both m...,"you had unprotected sex? it is your ""other"" he...",I'm here to provide you with information and g...,Experiencing irritation on the head of the pen...
23435,is there a coated naproxen medication to preve...,all over-the-counter and prescription-strength...,"Yes, there are coated naproxen medications ava...","Yes, there are formulations of naproxen that a..."
23436,what are some nonimpact activities for people ...,non-impact exercise program for people with os...,There are several non-impact activities that c...,"For people with osteoporosis, engaging in non-..."

### Making Chunks of the Input Data to be used for RAG

Let's analyze the distribution of characters in each gpt answer

In [8]:
comp_dataset['gpt_response_base'].apply(lambda x: len(x)).describe()

count    23437.000000
mean      1581.831506
std        599.059524
min          4.000000
25%       1134.000000
50%       1545.000000
75%       1970.000000
max       4259.000000
Name: gpt_response_base, dtype: float64

Let's use Chunk Size of 1000 and Overlap of 500. This will (on average) ensure that an answer gets divided into 3-4 chunks

In [9]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=500,
    length_function=len,
    is_separator_regex=False,
    separators=["\n\n", "\n", ".", " ",  ""],
)

Let's chunk the documents and save them into a unified list

In [10]:
gpt_response_chunks = []

for index, row in comp_dataset.iterrows():
    gpt_response_chunks = gpt_response_chunks + text_splitter.split_text(row['gpt_response_base'])

print(len(gpt_response_chunks))

62136

Let's generate the ids for each chunk

In [11]:
gpt_response_chunks_id = list(range(0, len(gpt_response_chunks)))
gpt_response_chunks_id = [str(id) for id in gpt_response_chunks_id]
len(gpt_response_chunks_id)

62136

### Setting up the Chroma Database

Create a persistent client to read the database from a defined directory

In [12]:
chromadb_client = chromadb.PersistentClient(path="./chroma_db")

Create or get the `kabatubare_dataset` collection

In [13]:
kabatubare_dataset_collection = chromadb_client.get_or_create_collection(name="kabatubare_dataset")

Chroma only allows a batch size of 5461 for addition. Let's prepare the batches with max size of 5000 and put them one by one into the collection

In [14]:
index_array = np.arange(start=0, stop=len(gpt_response_chunks), step=5000)
index_array = np.append(index_array, len(gpt_response_chunks))
index_array

array([    0,  5000, 10000, 15000, 20000, 25000, 30000, 35000, 40000,
       45000, 50000, 55000, 60000, 62136])

In [15]:
# for i in range(0, len(index_array)-1):
#     start = index_array[i]
#     end = index_array[i+1]
#     print(f"Adding {start} to {end}")
#     kabatubare_dataset_collection.add(
#         documents=gpt_response_chunks[start:end],
#         ids=gpt_response_chunks_id[start:end],
#     )

Let's see how many embeddings are stored in our collection

In [16]:
kabatubare_dataset_collection.count()

62136

Let's see the first five documents in our database

In [17]:
kabatubare_dataset_collection.get()['documents'][0:5]

["It's not uncommon for individuals to experience discomfort in the testicles after increased sexual activity, including frequent masturbation. Here are a few possibilities that could explain your symptoms:\n\n1. **Muscle strain**: Excessive stimulation can lead to muscle tension or strain in the pelvic area, potentially causing dull aches.\n\n2. **Refractory period**: After orgasm, it’s normal for the testicles and surrounding tissues to feel sensitive or ache due to the temporary changes in blood flow and hormone levels.\n\n3. **Epididymitis**: This is an inflammation of the epididymis (the tube that stores and carries sperm), which can sometimes occur after extensive sexual activity. Symptoms may include pain and swelling.\n\n4. **Testicular torsion or other acute conditions**: These are less likely, especially given that you mentioned no lumps or mass, but they can cause severe pain and require immediate medical attention.",
 "3. **Epididymitis**: This is an inflammation of the epididymis (the tube that stores and carries sperm), which can sometimes occur after extensive sexual activity. Symptoms may include pain and swelling.\n\n4. **Testicular torsion or other acute conditions**: These are less likely, especially given that you mentioned no lumps or mass, but they can cause severe pain and require immediate medical attention.\n\nIf the pain persists, worsens, or if you experience additional symptoms such as swelling, redness, or fever, it's advisable to seek medical evaluation to rule out any serious conditions. For mild and transient discomfort, taking breaks from activities, applying cold compresses, and over-the-counter pain relief might help. Always be mindful of your body's signals and don’t hesitate to consult a healthcare professional for personalized advice.",
 "During pregnancy, there are several dietary recommendations and precautions that can help ensure the health of both the mother and the developing baby. At 7 weeks, many women experience food aversions or cravings, but here are general guidelines on what to avoid or limit:\n\n### Foods to Avoid:\n1. **Raw or Undercooked Seafood, Meat, and Eggs**: Sushi that contains raw fish is generally discouraged due to the risk of foodborne illnesses and parasites. Cooked sushi (like eel or shrimp tempura) is usually safer.\n  \n2. **High-Mercury Fish**: Fish like shark, swordfish, king mackerel, and tilefish should be avoided due to high mercury levels, which can harm the baby's development.\n\n3. **Unpasteurized Dairy**: Avoid soft cheeses and unpasteurized milk as they may contain harmful bacteria like Listeria.\n\n4. **Processed Junk Foods**: High-sugar and high-salt foods should be minimized for overall health.",
 "3. **Unpasteurized Dairy**: Avoid soft cheeses and unpasteurized milk as they may contain harmful bacteria like Listeria.\n\n4. **Processed Junk Foods**: High-sugar and high-salt foods should be minimized for overall health.\n\n5. **Certain Herbs and Spices**: Some herbal teas and supplements may not be safe during pregnancy, so it's best to consult with a healthcare provider about specific herbs.\n\n### Foods to Limit:\n1. **Caffeine**: While moderate caffeine consumption (up to 200 mg per day, equivalent to about one 12-ounce cup of coffee) is generally considered safe, excessive caffeine can lead to complications.\n\n2. **Alcohol**: It is widely recommended to avoid alcohol entirely during pregnancy as it can affect fetal development.",
 "### Foods to Limit:\n1. **Caffeine**: While moderate caffeine consumption (up to 200 mg per day, equivalent to about one 12-ounce cup of coffee) is generally considered safe, excessive caffeine can lead to complications.\n\n2. **Alcohol**: It is widely recommended to avoid alcohol entirely during pregnancy as it can affect fetal development.\n\n### General Recommendations:\n- **Fruits and Vegetables**: Encourage a diverse intake, ensuring they're well-washed to avoid foodborne illness.\n- **Lean Proteins**: Cooked chicken, turkey, beans, and nuts are good options.\n- **Whole Grains**: Incorporate brown rice, whole-grain bread, and oats.\n- **Stay Hydrated**: Water, milk, and 100% fruit juices are ideal choices.\n\nYour healthcare provider is the best source of personalized advice, so it's important to follow their recommendations. If you have any specific questions or concerns, it may also be beneficial to consult with a registered dietitian who specializes in maternal health."]

Let's get some top-5 results for a dummy query to see if our system is working well

In [18]:
results = kabatubare_dataset_collection.query(
    query_texts=["What should I do if I have a headache?"],
    n_results=5
)

results

{'ids': [['31334', '11909', '23142', '61836', '48098']],
 'embeddings': None,
 'documents': [["It’s important to listen to your body. If the headache continues or worsens, or if you develop new symptoms (like fever, visual changes, nausea, or confusion), you should seek medical attention promptly. It's always better to err on the side of caution, especially when it comes to headaches or any potential reactions to substances like insect repellents.\n\nIf you decide to see a doctor, they may perform a physical examination and, if necessary, imaging or additional tests to help determine the cause of your symptoms. In the meantime, consider keeping hydrated, using a cold or warm pack on your neck, and practicing relaxation techniques to help alleviate tension.",
   '3. **Rest**: Ensure plenty of rest in a quiet and comfortable environment. Stress and fatigue can exacerbate headaches.\n\n4. **Cool Compress**: Applying a cool compress to the forehead or the back of the neck may help alleviate headache symptoms.\n\n5. **Caffeine**: In some cases, small amounts of caffeine can relieve headaches, but this should be approached cautiously, as it can increase blood pressure in some individuals.\n\n6. **Consult a Healthcare Professional**: If the headache and fever persist or are severe, or if there are other concerning symptoms (such as chest pain, shortness of breath, or changes in vision), seek medical attention immediately. \n\nAlways check with a healthcare professional who knows your medical history and current medications before making any changes to your treatment plan.',
   "2. **Seek Follow-Up Care**: It’s important to follow up with your primary care physician or a headache specialist. They might consider other treatment options such as preventive medications, lifestyle changes, or different types of therapies.\n\n3. **Consider a Neurologist**: Since your symptoms have persisted for over a week, seeing a neurologist may be beneficial. They can perform tests and evaluations to determine if there's an underlying condition that needs to be addressed.\n\n4. **Monitor Additional Symptoms**: Keep an eye on any new symptoms that arise, such as changes in vision, confusion, or severe balance issues. If you experience these, you may need to return to the emergency room.",
   "Given the seriousness of your symptoms and the duration of your headache and fever, it's imperative to seek medical treatment as soon as possible. Go to an emergency room or contact your healthcare provider. They can evaluate your condition, perform necessary tests, and provide you with appropriate treatment. Your health is the priority, so please don’t hesitate to get help.",
   "5. **Infection or illness**: Sometimes, the body's response to an infection can cause headaches along with chills or fever.\n\nIt's important to recognize that while there are home remedies and over-the-counter options that might help alleviate your symptoms, they won't address the underlying cause. Here are a few non-prescription steps you might consider:\n\n- **Hydration**: Make sure you're drinking enough water, as dehydration can cause headaches.\n- **Caffeine**: Sometimes a small amount of caffeine can help relieve headaches, but be cautious as too much can also have the opposite effect.\n- **Rest and Relaxation**: Ensure you are getting enough sleep and consider techniques such as deep breathing, meditation, or yoga to help manage stress.\n- **Cold or Warm Compress**: Applying a cold or warm pack to your head or neck may provide relief.\n- **Over-the-Counter Medications**: Non-prescription pain relievers like ibuprofen or acetaminophen might help alleviate headache pain."]],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[None, None, None, None, None]],
 'distances': [[0.5247520208358765,
   0.5315669775009155,
   0.5574415326118469,
   0.5728696584701538,
   0.6337801218032837]]}

In [19]:
results['documents'][0]

["It’s important to listen to your body. If the headache continues or worsens, or if you develop new symptoms (like fever, visual changes, nausea, or confusion), you should seek medical attention promptly. It's always better to err on the side of caution, especially when it comes to headaches or any potential reactions to substances like insect repellents.\n\nIf you decide to see a doctor, they may perform a physical examination and, if necessary, imaging or additional tests to help determine the cause of your symptoms. In the meantime, consider keeping hydrated, using a cold or warm pack on your neck, and practicing relaxation techniques to help alleviate tension.",
 '3. **Rest**: Ensure plenty of rest in a quiet and comfortable environment. Stress and fatigue can exacerbate headaches.\n\n4. **Cool Compress**: Applying a cool compress to the forehead or the back of the neck may help alleviate headache symptoms.\n\n5. **Caffeine**: In some cases, small amounts of caffeine can relieve headaches, but this should be approached cautiously, as it can increase blood pressure in some individuals.\n\n6. **Consult a Healthcare Professional**: If the headache and fever persist or are severe, or if there are other concerning symptoms (such as chest pain, shortness of breath, or changes in vision), seek medical attention immediately. \n\nAlways check with a healthcare professional who knows your medical history and current medications before making any changes to your treatment plan.',
 "2. **Seek Follow-Up Care**: It’s important to follow up with your primary care physician or a headache specialist. They might consider other treatment options such as preventive medications, lifestyle changes, or different types of therapies.\n\n3. **Consider a Neurologist**: Since your symptoms have persisted for over a week, seeing a neurologist may be beneficial. They can perform tests and evaluations to determine if there's an underlying condition that needs to be addressed.\n\n4. **Monitor Additional Symptoms**: Keep an eye on any new symptoms that arise, such as changes in vision, confusion, or severe balance issues. If you experience these, you may need to return to the emergency room.",
 "Given the seriousness of your symptoms and the duration of your headache and fever, it's imperative to seek medical treatment as soon as possible. Go to an emergency room or contact your healthcare provider. They can evaluate your condition, perform necessary tests, and provide you with appropriate treatment. Your health is the priority, so please don’t hesitate to get help.",
 "5. **Infection or illness**: Sometimes, the body's response to an infection can cause headaches along with chills or fever.\n\nIt's important to recognize that while there are home remedies and over-the-counter options that might help alleviate your symptoms, they won't address the underlying cause. Here are a few non-prescription steps you might consider:\n\n- **Hydration**: Make sure you're drinking enough water, as dehydration can cause headaches.\n- **Caffeine**: Sometimes a small amount of caffeine can help relieve headaches, but be cautious as too much can also have the opposite effect.\n- **Rest and Relaxation**: Ensure you are getting enough sleep and consider techniques such as deep breathing, meditation, or yoga to help manage stress.\n- **Cold or Warm Compress**: Applying a cold or warm pack to your head or neck may provide relief.\n- **Over-the-Counter Medications**: Non-prescription pain relievers like ibuprofen or acetaminophen might help alleviate headache pain."]

Now that our Chroma database is setup, all the chunks are inserted and the query is working well. It's time that we initiated the LLaMA Model and pass these chunks along with each query to see the performance of LLaMA

### Formatting the questions

For each question in test dataset, we need to form a question in the form of rag string which needs to be passed to model. For this we need to extract the context from Chroma Database and then put it in the form of RAG sring which will be passed as user query to the model

Defining the function to get context related to query

In [20]:
def get_context_query(question):
    # get top-5 results from the database
    query_context = kabatubare_dataset_collection.query(
        query_texts=[question],
        n_results=5
    )

    query_context = query_context['documents'][0]

    query_context_str = ""
    for context in query_context:
        query_context_str = query_context_str + context + "\n\n"
    
    return query_context_str

Specifying the rag query format and formatting the query in this format

In [21]:
rag_query_str = '''Answer the QUESTION below by utilizing the information highlighted in the CONTEXT relevant to the QUESTION.
The final ANSWER should be a complete and coherent response to the QUESTION and should not include any of the CONTEXT or QUESTION text.
-----------------
CONTEXT: {context}
-----------------
QUESTION: {query}
-----------------
ANSWER: 
'''

In [22]:
def data_questions_formatted(question):
    query_context_str = get_context_query(question)
    
    rag_query_str_formatted = rag_query_str.format(context=query_context_str, query=question)
    
    return rag_query_str_formatted

Generating the context and applying the formatting. This took around 15 minutes, so the result is saved and will be loaded from there

In [23]:
# test_dataset_questions = test_dataset['question']
# test_dataset_questions_formatted_rag = test_dataset_questions.progress_apply(data_questions_formatted)

# with open('phase4_kabatubare_medical/test_dataset_questions_formatted_rag.pkl', 'wb') as file:
#     pickle.dump(test_dataset_questions_formatted_rag, file)

In [24]:
with open('phase4_kabatubare_medical/test_dataset_questions_formatted_rag.pkl', 'rb') as file:
    test_dataset_questions_formatted_rag = pickle.load(file)

### Loading the LLaMA Model

In [25]:
with open('../hf_token.key', 'r') as f:
    hf_token = f.read()

model_id = "meta-llama/Llama-3.2-3B-Instruct"

Loading the model shards

In [26]:
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"
tokenizer.model_max_length = 4096

Loading the model shards

In [27]:
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.bfloat16, device_map="auto") # Must be float32 for MacBooks!
model.config.pad_token_id = tokenizer.pad_token_id # Updating the model config to use the special pad token

Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.01s/it]

Defining the `eos` token as the terminator to finish the sentences

In [28]:
terminators = [
    tokenizer.eos_token_id,
    tokenizer.convert_tokens_to_ids("<|eot_id|>")
]

Defining the function to get the LLaMA Responses

In [29]:
def get_llama_response(question_inputs: str):
    
    llama_inputs = [[{"role": "system", "content": "You are a medical knowledge assistant trained to provide information and guidance on various health-related topics."},
                     {"role": "user", "content": question}] for question in question_inputs]

    texts = tokenizer.apply_chat_template(llama_inputs, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(texts, padding="longest", truncation=True, return_tensors="pt")
    inputs = {key: val.to(model.device) for key, val in inputs.items()}
    temp_texts = tokenizer.batch_decode(inputs['input_ids'], skip_special_tokens=True)
    
    gen_tokens = model.generate(
        **inputs, 
        max_new_tokens=4096, 
        pad_token_id=tokenizer.pad_token_id, 
        eos_token_id=terminators,
        do_sample=True,
        temperature=0.7,
        # top_p=0.9
    )

    gen_text = tokenizer.batch_decode(gen_tokens, skip_special_tokens=True)
    gen_text = [i[len(temp_texts[idx]):] for idx, i in enumerate(gen_text)]
    
    return gen_text

Preparing the batches of the data

In [30]:
batch_size = 2
dataset_questions = test_dataset['question']
dataset_answers = test_dataset['answer']
dataset_questions_formatted = test_dataset_questions_formatted_rag
batch_indices = np.arange(0, len(dataset_questions), batch_size)
if batch_indices[-1] != len(dataset_questions):
    batch_indices = np.append(batch_indices, len(dataset_questions))

Running the batch inference to get responses from LLaMA

In [31]:
# question_list = []
# answer_list = []
# llama_responses = []
# for i in tqdm(range(0, len(batch_indices) - 1)):
#     questions_input = dataset_questions[batch_indices[i]:batch_indices[i+1]]
#     orig_answers = dataset_answers[batch_indices[i]:batch_indices[i+1]]
#     questions_formatted_input = dataset_questions_formatted[batch_indices[i]:batch_indices[i+1]]
#     llama_resp = get_llama_response(questions_formatted_input)
    
#     question_list = question_list + questions_input.to_list()
#     answer_list = answer_list + orig_answers.to_list()
#     llama_responses = llama_responses + llama_resp

# with open('phase4_kabatubare_medical/questions.pkl', 'wb') as file:
#     pickle.dump(question_list, file)
    
# with open('phase4_kabatubare_medical/answers.pkl', 'wb') as file:
#     pickle.dump(answer_list, file)

# with open('phase4_kabatubare_medical/llama_resp.pkl', 'wb') as file:
#     pickle.dump(llama_responses, file)

### Evaluaing the LLaMA Responses

Reading the questions, answers and LLaMA Responses for

In [32]:
with open('phase4_kabatubare_medical/questions.pkl', 'rb') as file:
    question_list = pickle.load(file)
    
with open('phase4_kabatubare_medical/answers.pkl', 'rb') as file:
    answer_list = pickle.load(file)

with open('phase4_kabatubare_medical/llama_resp.pkl', 'rb') as file:
    llama_responses = pickle.load(file)

In [33]:
question_list[0:10]

["i don't have periods due to taking nuvaring. how would i know if i was pregnant since i don't have any periods to miss? . the last two times i put the nuvaring in i put it in a day late. i have pregnancy symptoms and am wondering how soon i can take a pregnancy test for it to be accurate. i know you normally would take one several days after a missed period but i don't have periods.",
 "when you can't digest food. my daughter is 38 and when she eats the food just sits in her stomach and rots making her sick. she can't hardly eat anything yet her weight still climbs. she had her gallbladder removed several years ago and has had this problem ever since. dr. put her on reglin (she is off that now) but all it did was make her feel like she had chronic fatigue syndrome. help.",
 "8 wks post-hemorrhoidectomy. knife-like pain on b. m. too frequent b. m. anemic-still blood in stool on good diet/fiber. still have blood in stool and with bm. burning knife-like pain on bm. stools r soft or loose. excessive frequency/urges. not predictable. producing too much stool. throbbing discomfort lasts well after bm. on proctofoam iron-rich (for anemia post op) fiber-rich diet per dr. comment 3 wks ago by diff. colorectal dr not surgeon was 'not healed yet may need to go back in' but would not explain or elaborate",
 'i sometimes feel a mild discomfort under my left brest into my shoulder what could this be? . i have not had a problem with high blood pressure in the past but the last time i had it checked it was 172/92. i am diabetic and over weight. i smoke and am 43 years old. recently i have been getting dizzy and light headed. when i went to the dr. about this they said it was vertigo. . a lot of the time when i have the discomfort i feel the need to belch. i am worried. please advise.',
 "i had sex about 12 hours ago and i'm noticing a small patch of skin with redness in blotches but no pain nor pus. no puss no burning or tingling feels flat like my skin no lumps or bulge right above penis",
 'can you be allergic to mold in your food?',
 'if someone signs up for health insurance using the marketplace will there be open enrollment next year? . for if they want to make any changes.',
 'my wife has mono. can it be sexually transmitted without kissing? how long before we can have unprotected sex?',
 'aetna will not renew our health coverage next year. . what are the best options for a self-employed single income family with registered native american heritage in ca?',
 'do you need to experience a panic attack in order to have anxiety?']

In [34]:
answer_list[0:10]

["you really shouldn't worry about getting pregnanat while on birth control. your periods are being missed because of the birth control however that is completely normal. i would not be concerned with it at all",
 "i'm sorry your daughter is having a hard time. i think it's best for her to get checked out by a gastroenterologist to rule out any underlying problems. you can also have her see a registered dietitian to check for food intolerances and diet concerns related to gallbladder removal. here are some other things that might help: eat smaller more frequent meals. avoid high fat foods such as high fat meats full-fat dairy and fried foods. keep portions of fat (oil butter nuts/seeds) small at meals. get adequate fiber through fruits vegetables and whole grains. if fiber intake has been low gradually increase it. watch for individual items that are hard to digest such as dairy products and beverages like caffeine. have your daughter keep a journal to note which foods bother her (and in what quantities) and if possible troubleshoot with a dietitian. good luck! speaking to a medical practitioner has to be the best thing that you have to advise your daughter. do an action now before it is too late. it is just like the same quick action that you have to do in dealing with unwanted fats. you can also check out www. bodytreatmentcenter. com for a fat removal in nyc.",
 "i'm sorry you're going through this. hemorrhoidectomy is an unpleasant procedure and it's worse when post-surgical symptoms linger on for so long. i suggest you schedule a follow-up appointment with your surgeon. as the specialist he or she is in the best position to evaluate your situation and make recommendations for treatment if any. i think you've suffered long enough. recovery from hemorrhoid surgery generally only takes 2-4 weeks. why not give your surgeon a call for an appointment? wishing you all the best!",
 'after reading your full statement i would also suggest a second opinion.',
 'hi ok if your shaved and this is on your pubic bone could be just sore from grinding your pubic bone against you girl friends pubic bone give it a day or so should go away you could also try rubbing some aloe vera gel into it. good luck',
 'a person can have an allergic reaction to just about anything. so that would include food or molds.',
 "yes there will be open enrollment every year. next year's open enrollment period will be shorter than this years and will likely run from october through mid-december.",
 'mono can be transmitted by "intimate" contact but not necessarily from sexual activity which can involve face-to-face contact even if you restrain from kissing. the ebv virus (the cause of mono) has a long incubation period (many weeks) so you have most likely been exposed already. exposure to any infectious disease does not automatically mean you will get it since many people already have had mono in their lives and did not know it. because of past exposure or a mild form of mono that was not diagnosed in the past your sexual partner may have protective antibodies. mono is not considered a sexually transmitted disease but the closeness of this type of intimate encounter could spread the virus to a vulnerable person. or not. victims of mono are often very tired and exhausted so they may not be overly-interested in sexual activity but if your wife is feeling better (mono may not last more than a week in some mild cases) you can make a mutual decision keeping in mind that you were most likely exposed before you knew she had mono.',
 "start shopping for a new plan on your state's health insurance marketplace. you'll be able to compare plans side-by-side to see which best meets both your medical and financial needs.",
 "no you don't need to i have always been an excitable anxious child & adult & have experienced 5 panic attacks mostly due to a relationship problem you need to go to your dr & tell them councilling very good also & anti anxiety drugs also & maybe a low dose antidepressant hope this helps"]

In [35]:
llama_responses[0:10]

["If you're using NuvaRing and have missed it by a day a couple of times, it's understandable to be concerned about the possibility of pregnancy. Since you don't have regular periods while using hormonal contraception like NuvaRing, it can complicate understanding signs of pregnancy. \n\nTo determine if you're pregnant, you can take a home pregnancy test. For the most accurate result, it's generally recommended to wait at least a week after your missed period. However, since you don't have periods, you can take a pregnancy test as soon as you suspect you might be pregnant, but it's best to wait at least a week after the last time you had sex while using NuvaRing. \n\nKeep in mind that home pregnancy tests are most accurate when taken after a missed period, typically about 14 days after conception. Since you don't have periods, it's essential to consult a healthcare provider for guidance on the best time to take a pregnancy test and to discuss any concerns about your reproductive health.",
 "Given your daughter's symptoms of feeling like food sits in her stomach, causing discomfort, and her inability to digest food properly, it's likely she's experiencing gastroparesis. This condition involves delayed gastric emptying, leading to nausea, vomiting, and abdominal pain. Since she has a history of gallbladder removal and was previously on Reglin, it's possible that her body has adapted to manage the bile acid issue without a gallbladder, but the gastroparesis might be contributing to her symptoms.\n\nTo help manage her symptoms, encourage her to eat smaller, more frequent meals, and opt for soft, easily digestible foods like mashed potatoes, applesauce, yogurt, smoothies, cooked vegetables, tender meats, and fish. Limit high-fiber foods, as they can exacerbate the issue. It's also essential to maintain proper hydration by drinking plenty of fluids.\n\nConsidering her history of lactose intolerance and the fact that Reglin didn't provide sufficient relief, an elimination diet might be beneficial. She could try eliminating dairy products for a couple of weeks to see if her symptoms improve. If her symptoms resolve, reintroducing dairy can help determine if it's the cause. Additionally, consulting a pediatric gastroenterologist for further evaluation and guidance would be advisable.\n\nIt's concerning that her weight is still increasing despite her digestive issues. Regular monitoring of her weight and overall health, along with adjustments to her diet and lifestyle, can help her achieve a healthier weight. Encourage her to stay hydrated and consider incorporating lactose-free alternatives if lactose intolerance is suspected. A thorough evaluation and personalized advice from a healthcare professional are crucial in developing a comprehensive plan to address her symptoms and improve her overall well-being.",
 "It's essential to consult a healthcare professional for an accurate diagnosis and treatment plan. Given your symptoms of persistent blood in stool, burning pain during bowel movements, and soft or loose stools, it's crucial to rule out any complications that may have arisen after your hemorrhoidectomy. \n\nYou may want to discuss the following with your healthcare provider:\n\n1. **Re-evaluate the healing process**: Since your surgeon suggested that the surgical site may not be fully healed, it's possible that internal sutures are still causing irritation or pain. Your healthcare provider can assess the site and provide guidance on how to manage any ongoing discomfort.\n\n2. **Anal fissures or scar tissue**: Given your symptoms of pain and bleeding during bowel movements, it's possible that you may have developed an anal fissure or excess scar tissue. Your healthcare provider can perform a thorough examination to determine the cause of your symptoms.\n\n3. **Gastrointestinal conditions**: As you've mentioned blood in stool, it's essential to consider other potential causes such as diverticular disease, inflammatory bowel disease (IBD), polyps, or colorectal cancer. A thorough evaluation, including imaging studies or a repeat examination, may be necessary to determine the underlying cause.\n\n4. **Pain management**: Discuss a comprehensive pain management strategy with your healthcare provider to alleviate the burning, knife-like pain during bowel movements.\n\n5. **Fiber and iron intake**: While a high-fiber diet is beneficial, excessive fiber can sometimes lead to diarrhea or softer stools. Your healthcare provider can help you find a balance that works for you and address any potential interactions with your iron supplements.\n\n6. **Follow-up care**: Schedule a follow-up appointment with your surgeon to discuss the status of your healing process and any necessary further evaluation or intervention.",
 "The discomfort you're experiencing under your left breast, radiating into your shoulder, can have several potential causes, considering your medical history. Given your risk factors of diabetes, obesity, smoking, and a recent episode of high blood pressure, it's essential to take these symptoms seriously and seek medical attention. \n\nThe combination of your symptoms, including dizziness, lightheadedness, and the need to belch, suggests that there could be a gastrointestinal component, such as acid reflux or indigestion, which can sometimes mimic heart-related pain. However, your recent diagnosis of vertigo and the pressure in your shoulder could also indicate muscle tension or more serious conditions, such as cardiac issues.\n\nConsidering your medical history, it's crucial to rule out any cardiovascular problems, especially given your risk factors. Your high blood pressure reading of 172/92 is concerning, and your diabetes and smoking status further increase the likelihood of underlying cardiovascular issues.\n\nTo determine the cause of your symptoms, it's vital to consult a healthcare professional for a thorough evaluation. They may conduct tests such as an ECG, stress test, or blood work to evaluate your heart health, or refer you to a gastroenterologist if they suspect a gastrointestinal issue. In the meantime, reducing your risk factors, such as quitting smoking, managing your weight, and controlling your blood sugar and blood pressure, under the guidance of your healthcare provider, is advisable.\n\nGiven the complexity of your symptoms and medical history, it's recommended that you seek medical attention as soon as possible to ensure an accurate diagnosis and appropriate treatment.",
 "Given the symptoms you've described, it's possible that the redness could be due to irritation or friction from sexual activity, which might have caused post-inflammatory erythema. However, since the redness is described as blotches and there's no pain, burning, or other symptoms, it's also possible that it could be a pearly penile papule or a small, harmless growth that appears on the head of the penis. It's essential to consult a healthcare provider or a dermatologist for a proper evaluation and accurate diagnosis. They can assess the area and provide guidance on the best course of action, which may include tests to determine the exact cause and appropriate treatment options if necessary. In the meantime, try to avoid any further irritation and keep the area clean and dry.",
 'Yes, it is possible to be allergic to mold present in food. Ingesting moldy food can cause symptoms like respiratory issues, skin rashes, gastrointestinal distress, and in severe cases, anaphylaxis. If you suspect a mold allergy or experience symptoms after consuming certain foods, consult a healthcare professional for proper testing and guidance.',
 'Yes, if someone signs up for health insurance through the marketplace, they will have the opportunity to make changes to their existing coverage during the open enrollment period the following year. This typically occurs annually, although the specific dates can vary. For example, the open enrollment period for 2024 coverage is expected to begin on November 1, 2023, and end on December 15, 2023, allowing individuals to review and adjust their plans for the upcoming year.',
 "It is highly unlikely that EBV, the primary cause of mononucleosis, is transmitted through sexual intercourse, as there is limited evidence to suggest that it is transmitted through this route. Most cases of EBV are spread through saliva and close personal contact rather than sexual activity. As long as your wife is not exhibiting symptoms, the risk of transmission is relatively low. The primary factor in determining when it's safe to resume unprotected sex is her recovery from the infection, typically around 4 to 6 weeks. It's essential to consult with her healthcare provider for personalized recommendations and confirm her recovery before engaging in any intimate activities.",
 'As a self-employed single-income family with registered Native American heritage in California, you have several options to explore for health coverage. Considering your heritage, you may be eligible for Medicaid, which offers free or low-cost health coverage based on income and household size. Additionally, you can explore Covered California, the state marketplace, which provides premium subsidies or cost-sharing reductions based on income. You can also look into Tribal Health Services, which often provide services to Native Americans regardless of income. Furthermore, as a Native American, you are eligible for Medicaid expansion under the Affordable Care Act, which provides comprehensive health coverage. You may also want to consider short-term health insurance plans, private health insurance options, nonprofit and local assistance programs, catastrophic health plans, and consulting a healthcare navigator to understand your personalized options.',
 'No, you do not need to experience a panic attack to have anxiety. Anxiety can manifest in various forms and intensities, and not everyone with anxiety disorders will experience panic attacks. Anxiety can present as generalized anxiety, social anxiety, or specific phobias, among other types. Symptoms may include excessive worry, restlessness, irritability, difficulty concentrating, and physical symptoms such as muscle tension or sleep disturbances.']

### Calculating the BLEU Score

In [36]:
bleu_eval = evaluate.load("bleu")
bleu_results = bleu_eval.compute(predictions=llama_responses, references=answer_list)
bleu_results

{'bleu': 0.014839747585239442,
 'precisions': [0.18641252802678335,
  0.025962690825557532,
  0.005832906217089278,
  0.0017178936095845077],
 'brevity_penalty': 1.0,
 'length_ratio': 1.3371639299232647,
 'translation_length': 686397,
 'reference_length': 513323}

### Calculating the ROUGE Score

In [37]:
rouge_eval = evaluate.load("rouge")
rouge_results = rouge_eval.compute(predictions=llama_responses, references=answer_list)
rouge_results

{'rouge1': np.float64(0.21963687293431416),
 'rouge2': np.float64(0.03944759827752637),
 'rougeL': np.float64(0.12723713951727206),
 'rougeLsum': np.float64(0.13632344682345307)}